### ISSUE TITLE
Setting log level to warn doesn't work

### ISSUE THREAD

**Issue by bushev** [ivanmarban/winston-telegram#1]
``` javascript
logger.add(winston.transports.Telegram, {
    level: 'warning',
    token: env.TELEGRAM_LOGGER_BOT_TOKEN,
    chatid: env.TELEGRAM_LOGGER_BOT_CHAT_ID
});
```

Both messages were logged (but should only one):

``` javascript
logger.info('Application started');
logger.warn('Application started');
```

This is a work around, how to set log level. After such configuration only warning are presents.

``` javascript
logger.transports.undefined.level = 'warning';
```

Issues:
1. Setting log level to warn doesn't work
2. Telegram transport name is 'undefined' on `logger.transports`

**Comment by ivanmarban** [comment]
Thanks for the feedback.
Setting log level as an option is actually not supported. I'll try to add it over the next few days when I have some free time. Feel free to make a PR.

**Comment by ivanmarban** [comment]
Added log level options in v0.2.0
