### ISSUE TITLE
Multiple Log-Levels

### ISSUE THREAD

**Issue by tvld** [ivanmarban/winston-telegram#2]
Great idea! 

Would it be possible to use different log levels going to different channels? I'd like warnings go to notify-silent Telegram channels, but send errors to a Telegram channel that give me a notification...

**Comment by ivanmarban** [comment]
Maybe could be used the `disable_notification` Telegram parameter to send the [message silently](https://telegram.org/blog/channels-2-0#silent-messages)

If you still want different log levels going to different channels, you could declare different loggers with different options.

**Comment by tvld** [comment]
If declaring different loggers does not introduce much overhead. Maybe you could extend your README with an example of how that would work?

**Comment by ivanmarban** [comment]
Check out latest version and take a look at the examples.

**Comment by tvld** [comment]
Super. Seems very convenient solution. Will have a look this week :+1:
