### ISSUE TITLE
Winston Transport can only be default-imported using the 'esModuleInterop' flag

### ISSUE THREAD

**Issue by thundo** [ivanmarban/winston-telegram#25]
Hi, I get this error while importing without using the `esModuleInterop` flag.

```
> tsc

node_modules/winston-telegram/lib/winston-telegram.d.ts:1:8 - error TS1259: Module '"D:/Projects/project/node_modules/winston-transport/index"' can only be default-imported using the 'esModuleInterop' flag

1 import TransportStream from "winston-transport"
         ~~~~~~~~~~~~~~~

  node_modules/winston-transport/index.d.ts:37:1
    37 export = TransportStream;
       ~~~~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

Shouldn't `winston-trasport` be imported with `=`?

**Comment by ivanmarban** [comment]
Hi, sorry but I'm not familiar with TypeScript. I will try to figure out your problem if I have some time.

**Comment by thundo** [comment]
I think this should point you in the right direction https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

The change, if I'm not mistaken, should be pretty simple:
`import TransportStream from "winston-transport"`
to
`import TransportStream = require("winston-transport")`

Thank you for your time

**Comment by ivanmarban** [comment]
@thundo could you please try branch hotfix/v2.3.4 ?

**Comment by thundo** [comment]
@ivanmarban yes, it works :)

Thanks
