### ISSUE TITLE
Unmet Peer Dependency

### ISSUE THREAD

**Issue by tvld** [ivanmarban/winston-telegram#3]
After `npm install -save winston` I get on running `npm install -save winston-telegram`:

```
├── UNMET PEER DEPENDENCY vows@
└── winston-telegram@0.3.0 
```

I looked at `vows`  and dont think I want it. Is it needed? Can we get it out?

**Comment by ivanmarban** [comment]
You can ignore this warning as vows is only used for unit testings purposes. This behaviour is related to npm@3:

> NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead. The behavior in npms 1 & 2 was frequently confusing and could easily put you into dependency hell, a situation that npm is designed to avoid as much as possible.

**Comment by ivanmarban** [comment]
- Remove _peerDependencies_ from package.json
- Add _vows_ dependency to _devDependencies_ in package.json

**Comment by ivanmarban** [comment]
Removed _peerDependencies_ in v0.4.0
