### ISSUE TITLE
[Suggestion/FR] Selective logging to telegram

### ISSUE THREAD

**Issue by nicoandmee** [ivanmarban/winston-telegram#38]
I find this (and slack transport) very useful- but only in a handful of cases, where I need to announce something important. Otherwise it becomes impossible with all the noise. I may be blind but AFAIK there isn't anything the library provides, to make it possible to selectively send some messages to TG. For instance, I'm wanting to do this:

```js
// something horrible happened, send help
logger.debug('Red Alert!', { chatId: process.env.TEAM_CHAT_ID })
```

I think maybe it can identify the parameter in the metadata object, and when that's present, use the transport. Is this possible to your knowledge? Thanks!

**Comment by ivanmarban** [comment]
I'm not sure if I understand correctly but does [this feature](https://github.com/winstonjs/winston#filtering-info-objects) of winston do what you are requesting ?

Could you provide a complete example of your needs ?

**Comment by ivanmarban** [comment]
Let me know if this is what are you looking for:

```javascript
const { createLogger, format, transports } = require('winston')
const TelegramLogger = require('winston-telegram')

// Ignore log messages if they have { private: true }
const ignorePrivate = format((info, opts) => {
  if (info.private) { return false }
  return info
})

const logger = createLogger({
  format: format.combine(
    ignorePrivate(),
    format.json()
  ),
  transports: [
    new transports.Console(),
    new TelegramLogger({
      token: 'TOKEN',
      chatId: 'CHAT_ID',
      level: 'error',
      unique: true
    })
  ]
})

// Outputs: {"level":"error","message":"Public error to share"}
logger.log({
  level: 'error',
  message: 'Public error to share'
})

// Messages with { private: true } will not be written when logged.
logger.log({
  private: true,
  level: 'error',
  message: 'This is super secret - hide it.'
})
```

**Comment by nicoandmee** [comment]
> 

In a way yes but I was more thinking - not to ignore messages, but rather to selectively send them to Telegram, if `{private: true}` let's say in this instance. I know at a previous job we had this, just a slack bot instead of TG.
It would be invoked like this: `logger.info('Login Success', { channel: '@nico' })`. <-- This would go to channel specified.
But `logger.info('cache-hit-1337')` <-- this would only go to console.

**Comment by fr20587** [comment]
There is an example for NestJS?

**Comment by ivanmarban** [comment]
Sorry @fr20587 but I'm not familiar with NesJS.

@nicoandmee I'm sorry but I wasn't able to find time to take a look at your proposition for the moment.

**Comment by WildEgor** [comment]
@nicoandmee you can try my fork:
https://github.com/WildEgor/winston-telegram

https://github.com/WildEgor/winston-telegram/blob/develop/examples/simple-log/src/index.ts#L26

**Comment by ivanmarban** [comment]
After checking again @nicoandmee request, from my understanding, I think that there are two things:
- Be able to selectively choose what transport to use to log the message with a unique logger defined. Not possible AFAIK
- Be able to selectively choose what TG chatId should the log message be sent. That is the example from @WildEgor fork.

I'm closing this issue as there wasn't any activity or response since my last comment.
