### ISSUE TITLE
Add a new option for "message_thread_id" in chats

### ISSUE THREAD

**Issue by BrandPVP** [ivanmarban/winston-telegram#40]
This is an option for chats with threads enabled.

<html>
<body>

message_thread_id | Integer | Optional. Unique identifier of a message thread to which the message belongs; for supergroups only
-- | -- | --

</body>
</html>

**Comment by WildEgor** [comment]
@BrandPVP I guess repo is not maintained and you can try my fork (wip):
https://github.com/WildEgor/winston-telegram

Your feature:
https://github.com/WildEgor/winston-telegram/blob/develop/examples/simple-log/src/index.ts#L31

**Comment by ivanmarban** [comment]
@WildEgor this repository is not dead. I try to maintain it when I have free time, although it is true that I have not had it lately. Contributions are always appreciated. If you like to add any kind of feature to this project, fell free to make a PR.

**Comment by ivanmarban** [comment]
Added support for `message_thread_id` in v2.7.0
